version: 2
jobs:
  build:
    working_directory: ~/cassia-ruby
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test

    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Configure Bundler
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - cassia-ruby-{{ checksum "Gemfile.lock" }}
            - cassia-ruby-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: cassia-ruby-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Setup the environment
      - run: cp .sample.env .env

      # Run rspec in parallel
      - run:
          name: Run rspec in parallel
          command: bundle exec rspec
      
      # Save test results for timing analysis
      - store_test_results:
          path: test_results
   